language: java

cache:
  directories:
  - $HOME/.m2

script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)

services:
  - docker

before_install:
- docker run -p 5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=nimda --name cdb -d couchdb:2.3
